apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: 
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx-container
        image: nginx:{{ .Values.deployment.version }}
        ports:
        - containerPort: 80
